import type { Metadata } from 'next'
import { DM_Sans, Syne } from 'next/font/google'
import { Providers } from '@providers/index'

import '@styles/reset.scss'
import '@styles/globals.scss'

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin']
})

const syne = Syne({
  variable: '--font-syne',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${dmSans.variable} ${syne.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
