export const LIMITS = {
  MESSAGE_MAX_LENGTH: 2000,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
  NAME_MAX_LENGTH: 40,
  GROUP_NAME_MAX: 50,
  GROUP_MAX_MEMBERS: 500,
  FILE_MAX_SIZE_MB: 25
} as const
